/**:
  ros__parameters:
    min_longitudinal_offset: 0.410
    max_longitudinal_offset: -0.025
    min_lateral_offset: 0.270
    max_lateral_offset: 0.280
    min_height_offset: 0.325
    max_height_offset: 0.700
